name: Release

on: # 在什么时候执行
  workflow_run: # 在main分支的ci这个工作流，执行完成以后
    workflows: [ci]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: github.event.workflow_run.conclusion == 'success' # 如果上面的工作流执行成功
    timeout-minutes: 10 # 超时时间
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.15.1

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
